mode: pretrain_tnet
cuda: true
ngpu: 4

tnet_checkpoint: ~
mnet_checkpoint: ~
shm_checkpoint: ~

data_root: /root/datasets/Matting/Adobe_DIM/
batch_size: 32
lr: 0.0001
weight_decay: 0.0005
max_epoch: 100
loss_lambda: 0.01    # trade-off between prediction loss and classification loss

sample_period: 20
checkpoint_period: 20