mode: pretrain_mnet
cuda: true
ngpu: 4

tnet_checkpoint: ~
mnet_checkpoint: ~
shm_checkpoint: ~

data_root: /root/datasets/Matting/Adobe_DIM/
batch_size: 24
lr: 0.0001
weight_decay: 0.0005
max_epoch: 2
loss_lambda: 0.01    # trade-off between prediction loss and classification loss

sample_period: 1
checkpoint_period: 1