mode: pretrain_mnet
cuda: true
ngpu: 2

mnet_checkpoint: checkpoint-epoch20.pth.tar

data_root: /root/datasets/Matting/Adobe_DIM/
batch_size: 32
lr: 0.0001
weight_decay: 0.0005
max_epoch: 50
loss_lambda: 0.01    # trade-off between prediction loss and classification loss

sample_period: 1
checkpoint_period: 5